# Generated by Django 5.2.17 on 2026-09-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('sort_order', models.IntegerField(default=0, verbose_name='표시 순서')),
            ],
            options={
                'verbose_name': '운동 카테고리',
                'verbose_name_plural': '운동 카테고리',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='운동 목적')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('sort_order', models.IntegerField(default=0, verbose_name='표시 순서')),
            ],
            options={
                'verbose_name': '운동 목적',
                'verbose_name_plural': '운동 목적',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='상품명')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='슬러그')),
                ('short_description', models.CharField(max_length=300, verbose_name='요약')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('difficulty', models.CharField(choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('ADVANCED', '고급')], max_length=20, verbose_name='난이도')),
                ('duration_weeks', models.PositiveSmallIntegerField(verbose_name='기간(주)')),
                ('sessions_per_week', models.PositiveSmallIntegerField(verbose_name='주당 운동 횟수')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('thumbnail_object_key', models.CharField(max_length=500, verbose_name='썸네일 객체 키')),
                ('status', models.CharField(choices=[('DRAFT', '작성 중'), ('PUBLISHED', '판매 중'), ('SUSPENDED', '판매 중지')], default='DRAFT', max_length=20, verbose_name='판매 상태')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 공개시각')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='카테고리')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='trainers.trainerprofile', verbose_name='판매자')),
            ],
            options={
                'verbose_name': '운동 루틴 상품',
                'verbose_name_plural': '운동 루틴 상품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.exercisegoal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': '상품 운동 목적',
                'verbose_name_plural': '상품 운동 목적',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='goals',
            field=models.ManyToManyField(related_name='products', through='products.ProductGoal', to='products.exercisegoal', verbose_name='운동 목적'),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='찜한 시각')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='버전')),
                ('object_key', models.CharField(max_length=500, unique=True, verbose_name='S3 객체 키')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(max_length=100, verbose_name='MIME 유형')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='파일 크기')),
                ('checksum_sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('is_current', models.BooleanField(default=True, verbose_name='현재 버전')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드시각')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '운동 루틴 파일',
                'verbose_name_plural': '운동 루틴 파일',
                'ordering': ['product', '-version'],
                'constraints': [models.UniqueConstraint(fields=('product', 'version'), name='uniq_product_file_version'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('product',), name='uniq_current_product_file'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='product_file_version_at_least_one'), models.CheckConstraint(condition=models.Q(('size_bytes__gte', 1)), name='product_file_size_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='productgoal',
            constraint=models.UniqueConstraint(fields=('product', 'goal'), name='uniq_product_goal'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created_at'], name='products_pr_status_36c7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'difficulty', 'price'], name='products_pr_categor_5822a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='products_pr_seller__2449b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('duration_weeks__gte', 1)), name='product_duration_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sessions_per_week__gte', 1), ('sessions_per_week__lte', 14)), name='product_sessions_between_1_and_14'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_user_wishlist_product'),
        ),
    ]
