# Generated by Django 5.2.17 on 2026-09-08 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='주문 상태')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='총 주문금액')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료시각')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소시각')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='상품명 스냅샷')),
                ('seller_name', models.CharField(max_length=100, verbose_name='판매자명 스냅샷')),
                ('unit_price', models.PositiveIntegerField(verbose_name='주문 당시 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시각')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='상품')),
                ('product_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productfile', verbose_name='구매 파일 버전')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='trainers.trainerprofile', verbose_name='판매자')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='요청 IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='브라우저 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발급시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_logs', to='orders.orderitem', verbose_name='주문 상품')),
            ],
            options={
                'verbose_name': '다운로드 기록',
                'verbose_name_plural': '다운로드 기록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가시각')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='장바구니')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '장바구니 상품',
                'verbose_name_plural': '장바구니 상품',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_product')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'created_at'], name='orders_orde_buyer_i_1adc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'paid_at'], name='orders_orde_status_e8f3be_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='paid_order_has_paid_at'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='cancelled_order_has_cancelled_at'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller', 'created_at'], name='orders_orde_seller__d8f1ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='uniq_order_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['user', 'created_at'], name='orders_down_user_id_55cfc6_idx'),
        ),
    ]
