# Generated by Django 5.2.17 on 2026-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='외부 결제키'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='결제수단'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=30, verbose_name='결제 제공자'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='영수증 URL'),
        ),
    ]
