# Generated by Django 5.2.17 on 2026-09-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(max_length=100, verbose_name='전문 운동 분야')),
                ('career_years', models.PositiveSmallIntegerField(verbose_name='경력 연수')),
                ('career_description', models.TextField(verbose_name='경력 상세')),
                ('introduction', models.TextField(verbose_name='자기소개')),
                ('activity_url', models.URLField(blank=True, verbose_name='활동 URL')),
                ('status', models.CharField(choices=[('PENDING', '심사 대기'), ('APPROVED', '승인'), ('REJECTED', '거절')], default='PENDING', max_length=20, verbose_name='상태')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='거절 사유')),
                ('submitted_at', models.DateTimeField(verbose_name='제출시각')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='심사시각')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trainer_applications', to=settings.AUTH_USER_MODEL, verbose_name='심사자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_application', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '트레이너 인증 신청',
                'verbose_name_plural': '트레이너 인증 신청',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='자격증명')),
                ('issuer', models.CharField(max_length=150, verbose_name='발급기관')),
                ('country_code', models.CharField(default='KR', max_length=2, verbose_name='국가 코드')),
                ('credential_number', models.CharField(blank=True, max_length=100, verbose_name='자격번호')),
                ('evidence_object_key', models.CharField(max_length=500, verbose_name='증빙 객체 키')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드시각')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='trainers.trainerapplication', verbose_name='인증 신청')),
            ],
            options={
                'verbose_name': '트레이너 자격',
                'verbose_name_plural': '트레이너 자격',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(max_length=100, verbose_name='대표 전문 분야')),
                ('career_years', models.PositiveSmallIntegerField(verbose_name='경력 연수')),
                ('introduction', models.TextField(verbose_name='공개 자기소개')),
                ('activity_url', models.URLField(blank=True, verbose_name='활동 URL')),
                ('is_verified', models.BooleanField(default=True, verbose_name='인증 여부')),
                ('verified_at', models.DateTimeField(verbose_name='승인시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '트레이너 프로필',
                'verbose_name_plural': '트레이너 프로필',
                'ordering': ['user__nickname'],
            },
        ),
        migrations.AddIndex(
            model_name='trainerapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='trainers_tr_status_903d15_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainerapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('reviewed_by__isnull', False), ('reviewed_at__isnull', False)), _connector='OR'), name='trainer_approved_has_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='trainerapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='trainer_rejected_has_reason'),
        ),
    ]
