# Generated by Django 5.2.17 on 2026-09-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(verbose_name='평점')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('is_visible', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.orderitem', verbose_name='구매 항목')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_visible'], name='reviews_rev_product_09275e_idx')],
                'constraints': [models.UniqueConstraint(fields=('author', 'product'), name='uniq_author_product_review'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
